// BAR CHART
export const REQUEST_CHART_DATA = "REQUEST_CHART_DATA";
export const RECEIVE_CHART_DATA = "RECEIVE_CHART_DATA";
// SCATTERPLOT CHART
export const REQUEST_SCATTERPLOT_CHART_DATA = "REQUEST_SCATTERPLOT_CHART_DATA";
export const RECEIVE_SCATTERPLOT_CHART_DATA = "RECEIVE_SCATTERPLOT_CHART_DATA";
export const RECEIVE_SCATTERPLOT_CHART_DATA_ASYNC =
  "RECEIVE_SCATTERPLOT_CHART_DATA_ASYNC";
// HEATMAP CHART
export const REQUEST_HEATMAP_CHART_DATA = "REQUEST_HEATMAP_CHART_DATA";
export const RECEIVE_HEATMAP_CHART_DATA = "RECEIVE_HEATMAP_CHART_DATA";
